{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (printf "%s" .Release.Name) }}
  labels:
    app.kubernetes.io/name: piqc
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
